### ISSUE TITLE
combined_tally idea

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/ds-pipelines-3-course#17]
https://github.com/jread-usgs/ds-pipelines-3/issues/10#issuecomment-637704282

**Comment by aappling-usgs** [comment]
Jordan's suggestion is in response to instructions to add
```
obs_tallies <- scmake('obs_tallies_promise', remake_file='123_state_tasks.yml')
```
and return `obs_tallies` and also call it `obs_tallies` in *remake.yml*

**Comment by jread-usgs** [comment]
Yeah, but I realized that once you added the second `final_targets` output, that pattern doesn't work anymore. 

Let me publish my running list of notes on the repo...one sec

**Comment by jread-usgs** [comment]
My other notes are here (totally in **draft** form) https://github.com/USGS-R/ds-pipelines-3-course/issues/18

**Comment by jread-usgs** [comment]
maybe it does work that way. I am working through it and 🤐 until I understand it more

**Comment by aappling-usgs** [comment]
I think `remake::fetch` is probably the way to go instead
