### ISSUE TITLE
Error: hash not found

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/ds-pipelines-3-course#20]
When I switch from scmake() to loop_tasks() in task 6x, everything seems to run fine until the combiners, at which point I get this error:

<img width="759" alt="image" src="https://user-images.githubusercontent.com/12039957/83584561-84417500-a515-11ea-86eb-dfcee78f2426.png">

This has happened twice. At first I thought it was due to my scipiper PR changing how loop_tasks labels task-steps, but this time I'm not sure.

**Comment by aappling-usgs** [comment]
I get the same error for both combiner targets, with or without `force=TRUE` for making those targets.
<img width="759" alt="image" src="https://user-images.githubusercontent.com/12039957/83584690-e4381b80-a515-11ea-90b1-00f05f261bf0.png">
<img width="759" alt="image" src="https://user-images.githubusercontent.com/12039957/83584709-ed28ed00-a515-11ea-82bb-a0aef2621a90.png">

It's happening somewhere within `remake_update2`, which also gets called successfully for all of the task_steps before failing on the combiner.
<img width="550" alt="image" src="https://user-images.githubusercontent.com/12039957/83584807-2feac500-a516-11ea-9196-4ee0c208682b.png">

**Comment by aappling-usgs** [comment]
That particular hash does appear deep within the remake database of keys, but it doesn't appear to have a matching data file, which might be what the error is about.
<img width="576" alt="image" src="https://user-images.githubusercontent.com/12039957/83584871-5c064600-a516-11ea-9314-688b7415aeb8.png">

**Comment by aappling-usgs** [comment]
With some trial and error I can identify `AL_tally` as the missing mangled key in this case:
```
> remake_object <- remake:::remake(remake_file='remake.yml', verbose=FALSE, load_sources=FALSE)
>   dbstore <- remake_object$store$db
> scipiper:::get_mangled_key('AL_tally', dbstore)
[1] "QUxfdGFsbHk"
```

**Comment by aappling-usgs** [comment]
I can rebuild AL_tally as long as I use force=TRUE:
<img width="637" alt="image" src="https://user-images.githubusercontent.com/12039957/83585345-9e7c5280-a517-11ea-9c47-b38615fffcf6.png">
after which it becomes clear I need to rebuild AL_data for the same reason:
<img width="637" alt="image" src="https://user-images.githubusercontent.com/12039957/83585378-b81d9a00-a517-11ea-9424-06684f7e5c5b.png">

but then when I try to build one of the combiners again, I just hit a new hash that's missing. Where are all these hashes disappearing to??

**Comment by jread-usgs** [comment]
That is very odd. Especially since the combiners won't be run (to my knowledge) until the individual tasks are complete, and the final `scmake()` is called at the bottom of `loop_tasks`. So having behavior that differs from `scmake` seems odd.

**Comment by jread-usgs** [comment]
I took the version of the course that didn't have `loop_tasks`, so I didn't see it. 

But to try to run into your same issue, I did

```r
  loop_tasks(task_plan, task_makefile = remakefile)
  
  combined_tally <- scmake('combined_tally', remake_file = remakefile)
  timeseries_plots_info <- scmake('3_visualize/out/timeseries_plots.yml', remake_file=remakefile)
  
  timeseries_plots_info <- yaml::yaml.load_file('3_visualize/out/timeseries_plots.yml') %>%
    tibble::enframe(name = 'filename', value = 'hash') %>%
    mutate(hash = purrr::map_chr(hash, `[[`, 1))
```
Which worked fine although it is inefficient (since `scmake()` is also called within `loop_tasks`). But I probably walked myself into a corner with the way I implemented things w/o using promises and tried this quick fix to pivot to `loop_tasks`, so we probably have different implementations on how we use `loop_tasks`(?)

**Comment by aappling-usgs** [comment]
Thanks for trying it. Glad you didn't see the hash issue. I deleted the .remake folder and rebuilt and everything was fine again. That takes ~7 minutes for CONUS in this course, but it'd be a much bigger deal if this happened in a big project. And I still have no idea why. At least it doesn't happen everywhere all the time.

**Comment by aappling-usgs** [comment]
Your approach is pretty much where I was headed...so far I think we can drop the `scmake('3_visualize/out/timeseries_plots.yml'` but need to keep `combined_tally <- scmake('combined_tally'`. But given your comment, I'm looking harder into an option to use `remake::create_bindings()` or similar to load `combined_tally` without checking currentness.

**Comment by jread-usgs** [comment]
nice!

**Comment by aappling-usgs** [comment]
I've noted the potential hash issue in the course text in case anybody else coms across it.
